name: release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: release
        uses: google-github-actions/release-please-action@v4
        with:
          release-type: node
          include-v-in-tag: false
          extra-files: |
            README.md
      - if: ${{ steps.release.outputs.releases_created }}
        uses: ./.github/actions/release
        with:
          npm-stoken: ${{ secrets.NPM_TOKEN }}
